#Задаём имя рабочего потока
name: Build a JAR in spring boot using springboot

#๋Определяем ветки для запуска workflow
on:
  push:
    branches:
      - main

#Creating jobs
jobs:
  build:

  #Run app in different OS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]


    # Клонируем репозиторий
    steps:
    - uses: actions/checkout@v4


#установки зависимостей
    - name: Set up JDK 22
      uses: actions/setup-java@v1
      with:
        java-version: '22'

    - name: Build with Maven
      run: mvn clean install

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'

#запуск тестов
    - name: Run Tests
      run: mvn test


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy
        run: echo "Deploy deploy deploy ..."
